spring.application.name=GoodreadsORM
spring.datasource.url=jdbc:h2:file:~/goodreadsorm/src/main/goodreadsorm

spring.h2.console.settings.web-allow-others=true

spring.h2.console.enabled=true
spring.sql.init.mode=never
